# -*- coding: utf-8 -*-
"""json-assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DeDHZ2uijDo3nvm5UQI5c7d6GPWhIcMN
"""

import json

# -------------------------------
# Task 1 — Build a JSON Structure
# -------------------------------

user_profile = {
    "name": "Sathya",
    "age": 21,
    "email": "sathya@example.com",
    "is_active": True,
    "skills": ["Python", "AI", "Machine Learning"]
}

# Convert dictionary to JSON string
json_data = json.dumps(user_profile, indent=4)

print("Task 1 Output:")
print(json_data)


# -------------------------------
# Task 2 — Parse an API Response
# -------------------------------

api_response = '{"status": "success", "data": {"user_id": 101, "username": "alex99", "score": 87.5}}'

# Convert JSON string to Python dictionary
parsed_data = json.loads(api_response)

username = parsed_data["data"]["username"]
score = parsed_data["data"]["score"]

print("\nTask 2 Output:")
print("Username:", username)
print("Score:", score)
print(f"User {username} scored {score} points")


# -------------------------------
# Task 3 — Handle Nested JSON
# -------------------------------

data = {
    "name": "Priya",
    "address": {
        "city": "Bengaluru",
        "state": "Karnataka",
        "zip": "560001"
    }
}

# Extract city and zip
city = data["address"]["city"]
zip_code = data["address"]["zip"]

print("\nTask 3 Output:")
print("City:", city)
print("Zip Code:", zip_code)

# Add new key inside address
data["address"]["country"] = "India"

# Print updated JSON
print("\nUpdated JSON:")
print(json.dumps(data, indent=4))